### ISSUE TITLE
[GlobalStep] PHP Fatal error appears after updating the WooPayment plugin to 6.6.0-test-3 version. 

### ISSUE THREAD

**Issue by gglobalstep** [Automattic/woocommerce-payments#7446]
### Describe the bug
PHP Fatal error appears after updating the WooPayment plugin to 6.6.0-test-3 version. 

```
Fatal error: Uncaught ArgumentCountError: Too few arguments to function WC_REST_Payments_Payment_Intents_Controller::__construct(), 1 passed in /srv/users/user5389333d/apps/user5389333d/public/wp-content/plugins/woocommerce-payments/includes/class-wc-payments.php on line 1049 and exactly 4 expected in /srv/users/user5389333d/apps/user5389333d/public/wp-content/plugins/woocommerce-payments/includes/admin/class-wc-rest-payments-payment-intents-controller.php:83 
```

### Environment:
Woocommerce Version: WooCommerce  8.1.1
WooCommerce Payments: 6.6.0-test-3
WordPress version: v6.3.1

PC:
Windows 10,
Chrome(Version 117.0.5938.132)
Firefox (Version 118.0.1)

### Steps To Reproduce:

1. Create any test site.
2. Install and activate all the required plugins.
3. Install the latest stable version of WooCommerce Payments via WP-ADMIN -> Plugins page.
4. Complete WooCommerce Payments KYC flow.
5. Go to WP-ADMIN -> Plugins & click on Upload Plugin to upload the testing package(i.e.6.6.0-test-3 version).
6. Observe that, PHP Fatal error appears after updating the WooPayment plugin to 6.6.0-test-3 version. 

### Instruction Link:
https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows#plugin-update-via-plugins-page

### Actual behavior
PHP Fatal error appears after updating the WooPayment plugin to 6.6.0-test-3 version. 

###  Expected behavior
WooPayment plugin(6.6.0-test-3 version) should be updated successfully without any errors

### Video 

https://github.com/Automattic/woocommerce-payments/assets/41110392/38835953-a85c-4a1e-b2dd-9526a97b0aa1

*Isolating the problem (mark completed items with an [x]):*
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

<details>
`
### WordPress Environment ###
WC Version: 8.1.1
REST API Version: ✔ 8.1.1
WC Blocks Version: ✔ 10.9.3
Action Scheduler Version: ✔ 3.6.2
Log Directory Writable: ✔
WP Version: 6.3.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.57 (Unix) OpenSSL/1.0.2g
PHP Version: 8.0.30
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.33-0ubuntu0.16.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.1.1
WC Database Prefix: wp_
Total Database Size: 5.30MB
Database Data Size: 3.57MB
Database Index Size: 1.73MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.47MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
page: 7
post: 1
product: 1
shop_order: 1
wp_navigation: 1
wp_template: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (5) ###

Query Monitor: by John Blackbourn – 3.13.1
Code Snippets: by Code Snippets Pro – 3.5.0
Companion Plugin: by Osk – 1.30
WooCommerce Payments: by Automattic – 6.6.0-test-3
WooCommerce: by Automattic – 8.1.1

### Inactive Plugins (2) ###

Akismet Anti-Spam: Spam Protection: by Automattic - Anti Spam Team – 5.2
Hello Dolly: by Matt Mullenweg – 1.7.2

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class (Drop-in)

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Three
Version: 1.2
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### WooPayments ###

Version: 6.6.0-test-3
Connected to WPCOM: Yes
WPCOM Blog ID: 169572087
Account ID: acct_1NzgSxCOaKVyVIaJ
Payment Gateway: Enabled
Test Mode: Enabled
UPE: Enabled (deferred_intent_upe_with_fallback)
UPE Enabled APMs: card
WooPay: Enabled (no locations enabled)
WooPay Incompatible Extensions: No
Apple Pay / Google Pay: Enabled (product,cart,checkout)
Fraud Protection Level: basic
Multi-currency: Enabled
Public Key Encryption: Disabled
Auth and Capture: Enabled
Documents: Disabled
Logging: Enabled

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-10-11 13:55:41 +00:00
Options: ✔
Notes: 64
Onboarding: skipped

### Action Scheduler ###

Canceled: 1
Oldest: 2023-10-10 14:06:54 +0000
Newest: 2023-10-10 14:06:54 +0000

Complete: 10
Oldest: 2023-10-10 13:55:52 +0000
Newest: 2023-10-10 14:25:04 +0000

Failed: 1
Oldest: 2023-10-10 14:05:41 +0000
Newest: 2023-10-10 14:05:41 +0000

Pending: 1
Oldest: 2023-10-11 13:55:52 +0000
Newest: 2023-10-11 13:55:52 +0000

### Status report information ###

Generated at: 2023-10-10 14:56:00 +00:00
`

</details>

**Comment by leonardola** [comment]
I did some quick investigation. The error actually happens in version 6.5.1

This is how the line looks in 6.5.1:

https://github.com/Automattic/woocommerce-payments/blob/68d8c64bd578c0df887ec3de56e9e343328985e0/includes/class-wc-payments.php#L1049

This is how it looks in 6.6.0-test-3
https://github.com/Automattic/woocommerce-payments/blob/42d58a56c5018ac9dab0d69e5b5bb2dba45f0a7a/includes/class-wc-payments.php#L1049


Apparently not all files got updated when  the error happens.

**Comment by eduardoumpierre** [comment]
Thanks for investigating it further, @leonardola! A fix was discussed on this thread (p1696877278872479-slack-CGGCLBN58) and applied to the release branch. I confirmed that the [latest release](https://github.com/Automattic/woocommerce-payments/releases) fixed this issue.

**Comment by leonardola** [comment]
This seems related to #4438 and #7464
